services:
  app:
    build: .
    environment:
      DB_HOST:
      DATABASE_NAME:
      DATABASE_USERNAME:
      DATABASE_PASSWORD:
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
  db:
    image: postgres:16
    environment:
      POSTGRES_USERNAME:
      POSTGRES_PASSWORD:
    expose:
      - 5432
  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
networks:
  default:
    name: ruby_rover_network
