services:
  app:
    build: .
    environment:
      DB_HOST: db
      DATABASE_NAME: ruby_rover_development
      DATABASE_USERNAME: rails
      DATABASE_PASSWORD: rails
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
  db:
    image: postgres:16
    environment:
      POSTGRES_USERNAME: rails
      POSTGRES_PASSWORD: rails
    expose:
      - 5432
  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
networks:
  default:
    name: ruby_rover_default
