default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER_NAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  port: 5432

development:
  <<: *default
  database: ruby_rover_development

test:
  <<: *default
  database: ruby_rover_test

production:
  <<: *default
  database: ruby_rover_production
