service: ruby_rover

image: woodFordR/ruby_rover
servers:
  - PRODUCTION_SERVER

registry:
  username: woodFordR
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY

ssh:
  user: woodford
  password:
    - SSH_PASSWORD

# Use accessory services (secrets come from .env).
accessories:
  db:
    image: postgres:16
    host: 192.168.4.63
    port: 5432
  redis:
    image: redis:7.0
    host: 192.168.4.63
    port: 6379
    directories:
      - data:/data

# Configure a custom healthcheck (default is /up on port 3000)
healthcheck:
  path: /bird

asset_path: /rails/public/assets

# boot:
#   limit: 10 # Can also specify as a percentage of total hosts, such as "25%"
#   wait: 2
# primary_role: web
# allow_empty_roles: false
